export const CONTACT = {
  subtitulo: 'Contáctenos',
  titulo: 'Estamos aquí para ayudarle',
  descripcion: 'Comuníquese con nosotros para cualquier consulta sobre nuestros programas de formación continua.',
  imagenes: {
    fondo: 'assets/img/bg/header-img1.jpg',
  },
  info: {
    telefonoLabel: 'Teléfono',
    direccionLabel: 'Dirección',
    emailLabel: 'Correo electrónico',
    horarioLabel: 'Horario de atención',
  },
  alertas: {
    exitoTitulo: '¡Mensaje enviado!',
    exitoDescripcion: 'Nos pondremos en contacto con usted a la brevedad posible.',
    errorTexto: 'Ocurrió un error al enviar el mensaje. Por favor, intente nuevamente.',
  },
  form: {
    titulo: 'Envíenos un mensaje',
    nombreLabel: 'Nombre completo',
    nombrePlaceholder: 'Su nombre completo',
    telefonoLabel: 'Teléfono',
    telefonoPlaceholder: 'Su número de teléfono',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'Su correo electrónico',
    mensajeLabel: 'Mensaje',
    mensajePlaceholder: 'Escriba su mensaje aquí...',
    privacidadLabel: 'Acepto la política de privacidad',
    btnEnviar: 'Enviar mensaje',
    btnEnviando: 'Enviando...',
  },
  validacion: {
    nombreRequerido: 'El nombre es requerido.',
    nombreMinLength: 'El nombre debe tener al menos 3 caracteres.',
    nombreInvalido: 'El nombre solo puede contener letras y espacios.',
    telefonoInvalido: 'Ingrese un número boliviano válido (ej: 71234567).',
    emailRequerido: 'El correo electrónico es requerido.',
    emailInvalido: 'Ingrese un correo electrónico válido.',
    mensajeRequerido: 'El mensaje es requerido.',
    mensajeMinLength: 'El mensaje debe tener al menos 10 caracteres.',
    captchaRequerido: 'Ingrese el código de verificación.',
    privacidadRequerida: 'Debe aceptar la política de privacidad.',
  },
} as const;
